name: Useless
version: 0.8.8
main: elxris.SpiceCraft.SpiceCraft
author: elxris
website: http://dev.bukkit.org/server-mods/useless/
loadbefore: [Vault]
commands:
  tw:
    permission: useless.tw
  mbox:
    permission: useless.mail
  upin:
    permission: useless.upin
  lib:
    permission: useless.lib
  shop:
    permission: useless.shop
  cmd:
    permission: useless.cmd
  jbs:
    permission: useless.jobs
permissions:
  useless.tw:
    default: true
  useless.tw.noMaxTime:
    default: op
  useless.tw.noWarpLimit:
    default: op
  useless.tw.master:
    default: op
  useless.mail:
    default: true
  useless.mail.create:
    default: true
  useless.mail.massive:
    default: op
  useless.mail.noCharLimit:
    default: op
  useless.upin:
    default: true
  useless.upin.noLimit:
    default: op
  useless.cmd:
    default: true
  useless.cmd.reload:
    default: op
  useless.lib:
    default: true
  useless.lib.master:
    default: op
  useless.lib.buy:
    default: true
  useless.lib.sell:
    default: true
  useless.shop:
    default: true
  useless.shop.master:
    default: op
  useless.jobs:
    default: true
  useless.jobs.master:
    default: true
  useless.mob:
    default: true
