name: Useless
version: 0.8.5
main: elxris.Useless.Useless
commands:
    tw:
        description: Crea un warp temporal.
        usage: /tw
        permission: useless.tw
    mbox:
        description: Revisa tu bandeja.
        usage: /mbox
        permission: useless.mail
    mboxc:
        description: Elimina todos los mensajes de tu bandeja de mail.
        usage: /mboxc
        permission: useless.mail.create
    upin:
        description: Muestra en tu brujula la direccion que hayas marcado.
        usage: /upin
        permission: useless.upin
    lib:
        description: Funciona como una libreria.
        usage: /lib
        premission: useless.lib
    shop:
        description: A Shop.
        usage: /shop
        premission: useless.shop
    uselesslang:
        description: Cambia el idioma del plugin.
        usage: /uselesslang
        premission: useless.lang
permissions:
    useless.tw:
        default: true
    useless.tw.noMaxTime:
        default: op
    useless.tw.noWarpLimit:
        default: op
    useless.tw.master:
        default: op
    useless.mail:
        default: true
    useless.mail.create:
        default: true
    useless.mail.massive:
        default: op
    useless.mail.noCharLimit:
        default: op
    useless.upin:
        default: true
    useless.upin.noLimit:
        default: op
    useless.cmd.reload:
        default: op
    useless.lib:
        default: true
    useless.lib.master:
        default: op
    useless.lib.buy:
        default: true
    useless.lib.sell:
        default: true
    useless.shop:
        default: true
    useless.lang:
        default: op
    useless.mob:
    	default: true