name: Useless
version: 0.7.7c
main: elxris.Useless.Useless
commands:
    tw:
        description: Crea un warp temporal.
        usage: /tw
        permission: useless.tw
    mbox:
        description: Revisa tu bandeja.
        usage: /mbox
        permission: useless.mail
    mboxc:
        description: Elimina todos los mensajes de tu bandeja de mail.
        usage: /mboxc
        permission: useless.mail.create
    upin:
        description: Muestra en tu brujula la direccion que hayas marcado.
        usage: /upin
        permission: useless.upin
    lib:
        description: Funciona como una libreria.
        usage: /lib
        premission: useless.lib
permissions:
    useless.tw:
        default: true
    useless.tw.noMaxTime:
        default: false
    useless.tw.noWarpLimit:
        default: false
    useless.tw.master:
        default: false
    useless.mail:
        default: true
    useless.mail.create:
        default: true
    useless.mail.massive:
        default: false
    useless.mail.noCharLimit:
        default: false
    useless.upin:
        default: true
    useless.upin.noLimit:
        default: false
    useless.cmd.reload:
        default: false
    useless.lib:
        default: true
    useless.lib.master:
        default: false
    useless.lib.buy:
        default: true
    useless.lib.sell:
        default: true