name: SpiceCraft
version: 0.10.5
main: elxris.SpiceCraft.SpiceCraft
author: elxris
website: http://dev.bukkit.org/server-mods/useless/
loadbefore: [Vault]
commands:
  tw:
    permission: spicecraft.tw
  mbox:
    permission: spicecraft.mail
  upin:
    permission: spicecraft.upin
  lib:
    permission: spicecraft.lib
  shop:
    permission: spicecraft.shop
  cmd:
    permission: spicecraft.cmd
  /spicecraft:
    permission: spicecraft.reload
permissions:
  spicecraft.reload:
    default: op
  spicecraft.tw:
    default: true
  spicecraft.tw.noMaxTime:
    default: op
  spicecraft.tw.noWarpLimit:
    default: op
  spicecraft.tw.master:
    default: op
  spicecraft.mail:
    default: true
  spicecraft.mail.create:
    default: true
  spicecraft.mail.massive:
    default: op
  spicecraft.mail.noCharLimit:
    default: op
  spicecraft.upin:
    default: true
  spicecraft.upin.noLimit:
    default: op
  spicecraft.cmd:
    default: true
  spicecraft.cmd.reload:
    default: op
  spicecraft.lib:
    default: true
  spicecraft.lib.master:
    default: op
  spicecraft.lib.buy:
    default: true
  spicecraft.lib.sell:
    default: true
  spicecraft.shop:
    default: true
  spicecraft.shop.master:
    default: op
  spicecraft.shop.server.open:
    default: true
  spicecraft.shop.server.sell:
    default: true
  spicecraft.shop.server.buy:
    default: true
  spicecraft.shop.private.open:
    default: true
  spicecraft.shop.private.sell:
    default: true
  spicecraft.shop.private.buy:
    default: true
  spicecraft.monster:
    default: true
