name: Useless
version: 0.0.6.3
main: elxris.Useless.Useless
commands:
    tw:
        description: Crea un warp temporal.
        usage: /tw minutos
        permission: useless.tw
    mbox:
        description: Revisa tu bandeja.
        usage: /mbox ?
        permission: useless.mail
    mboxc:
        description: Elimina todos los mensajes de tu bandeja de mail.
        usage: /mboxc ?
        permission: useless.mail.create
    upin:
        description: Muestra en tu brujula la direccion que hayas marcado.
        usage: /upin set <x> <y> <z>
        permission: useless.upin
permissions:
    useless.tw:
        default: true
    useless.mail:
        default: true
    useless.mail.create:
        default: true
    useless.mail.massive:
        default: true
    useless.upin:
        default: true