# SpiceCraft by elxris
# Fork me on github: https://github.com/elxris/SpiceCraft
# Wiki on https://github.com/elxris/SpiceCraft/wiki
lang: en
tw:
  maxTime: 120
  minTime: 1
  maxPerUser: 2
  price: 20.0
  usePrice: 5.0
mail:
  serverUserName: "Server"
  maxChar: 200
  onLogin: true
  onLoginDelay: 5
  clearOnDays: 15
upin:
  maxPerUser: 10
lib:
  topSize: 3
  rate: 0.6
shop:
  ## Don't modify this unless you know what you are doing.
  multiplier: 4.0
  userMultiplier: 2.0
  sellRate: 1.0
  vel: 8
  freq: 1
  userVariation: 8
  userShopSize: 50
  variable: true
  defaultUserSell: true
  defaultUserBuy: true
econ:
  logg: true
comm:
  tw:
    new:
    - nuevo
    - new
    - n
    destroy:
    - destruir
    - destroy
    - d
    - eliminar
    - e
    - borrar
    - b
    list:
    - listar
    - lista
    - list
    - li
    - l
  mbox:
    count:
    - .
    read:
    - leer
    - l
    - read
    - r
    clear:
    - borrar
    - b
    - clear
    - c
    new:
    - nuevo
    - n
    - crear
    - c
    - new
    add:
    - agregar
    - añadir
    - a
    - add
    send:
    - enviar
    - e
    - send
    - s
    sendall:
    - atodos
    - t
    - sendall
    - sa
  upin:
    del:
    - delete
    - del
    - delete
    - borrar
    - b
    list:
    - listar
    - l
    - list
  lib:
    del:
    - delete
    - del
    - delete
    - borrar
    - b
    buy:
    - comprar
    - buy
    - c
    info:
    - info
    - i
    top:
    - top
    - t
    list:
    - list
    - listar
    - l
    sell:
    - vender
    - vende
    - sell
    - v
    - s
    pay:
    - paga
    - pay
    - p
  shop:
    help:
    - help
    - info
    - '?'
    set:
    - set
    reset:
    - reset
    userPrefix:
    - '@'
