
# Useles by elxris
# Fork me on github: https://github.com/elxris/Useless
lang:
- es
comm:
  tw:
    new:
    - nuevo
    - n
    destroy:
    - destruir
    - d
    - eliminar
    - e
    - borrar
    - b
    list:
    - listar
    - lista
    - list
    - li
    - l
  mbox:
    count:
    - .
    read:
    - leer
    - l
    - read
    - r
    clear:
    - borrar
    - b
    - clear
    - c
    new:
    - nuevo
    - n
    - crear
    - c
    - new
    add:
    - agregar
    - añadir
    - a
    - add
    send:
    - enviar
    - e
    - send
    - s
    sendall:
    - atodos
    - t
    - sendall
    - sa
  upin:
    del:
    - delete
    - del
    - delete
    - borrar
    - b
    list:
    - listar
    - l
    - list
  lib:
    del:
    - delete
    - del
    - delete
    - borrar
    - b
    buy:
    - compra
    - buy
    - c
    info:
    - info
    - i
    top:
    - top
    - t
    list:
    - list
    - listar
    - l
    sell:
    - vender
    - vende
    - sell
    - v
    - s
    pay:
    - paga
    - pay
    - p
  shop:
    sell:
    - sell
    - s
    - vender
    - v
